version: '3.3'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    ports:
      - 8098:80
    links:
      - php-fpm
    volumes:
      - ./:/var/www
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm.dockerfile
    volumes:
      - ./:/var/www
    links:
      - mysql
    environment:
      - DB_PORT=3306
      - DB_HOST=mysql
  php-cli:
    build:
      context: ./
      dockerfile: docker/php-cli.dockerfile
    volumes:
      - ./:/var/www
    links:
      - mysql
    environment:
      - DB_PORT=3306
      - DB_HOST=mysql
    tty: true
  mysql:
    image: mysql:5.7
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    ports:
      - 33061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_DATABASE=laravel
